Feature/00002
Zyoh/UdonSharp-Scripts pull request #2
Opened 2020-04-26 22:16 UTC by DeaThunder

2020-04-26 22:27 UTC, Zyoh requested changes

2020-04-26 22:27 UTC, Zyoh commented on FollowPlayer.cs
> +    private void FixedUpdate()
Revert to `Update()`

2020-04-30 20:57 UTC, DeaThunder commented on FollowPlayer.cs
> +    private void FixedUpdate()
Fixed

2020-04-30 21:01 UTC, Zyoh approved these changes
Sure

2020-04-30 21:01 UTC, merged